### ISSUE TITLE
Fix travis-ci

### ISSUE THREAD

**Issue by ayr-ton** [ayr-ton/awesome-geek-podcasts#8]
Currently, all builds are failing at travis-ci.

We could either migrate to something else (like circle.ci) or figure out what's happening with travis.

https://travis-ci.org/ayr-ton/awesome-geek-podcasts/builds/592248431

**Comment by Andy9822** [comment]
I'll have a look but I believe I can figure out what's wrong and fix it!

**Comment by Andy9822** [comment]
Hello @ayr-ton 
I could manage to solve your problem, Travis is back working properly with your project!

Just to mention:
Your first script `awesome_bot --allow-redirect README.md` is not passing the test or whatever) and it's exiting with 1.
The other 2 scripts are performing well and execute with non error return.

I suppose that's something related to your project so I think my part (or what I could do for you) is done :D

I'll be submitting the PR soon, I'll just double check everything is ok.

**Comment by ayr-ton** [comment]
Thanks, @Andy9822 \o/
